In [1]:
import numpy as np
a=np.array([5,6,9])
a[0]

5

In [2]:
#declaring 2D
a=np.array([[1,2],[3,4],[5,6]])
a.ndim #ndim is used to print dimension

2

In [3]:
a.itemsize #print data size

4

In [4]:
a.size 

6

In [5]:
a.shape #represents info for width and height

(3, 2)

In [6]:
#dtype is used to specify data type
a=np.array([[1,2],[3,4],[5,6]] , dtype=complex)
a


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [7]:
import numpy as np  #once function
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#arange function
np.arange(1,5)
np.arange(1,6,2) #here 2 is no of steps
np.linspace(1,5,10) #specify first&last and generate no 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
#reshape function
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#ravel function is used to flaten the array but it doesn't gonna alert your original array 
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [15]:
#min and max and sum functions
a.min()
a.max()
a.sum()

21

In [16]:
#axis function
a.sum(axis=0) #here 0 means adding columns whereas 1 means adding rows

array([ 9, 12])

In [17]:
#sqrt function
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [18]:
np.std(a) #std is standard deviation

1.707825127659933